# Generated by Django 4.2.5 on 2023-09-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiringlink',
            options={'verbose_name': 'Expiring Link', 'verbose_name_plural': 'Expiring Links'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
