# Generated by Django 4.2.5 on 2023-09-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_image_name_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='picture.image'),
        ),
    ]
