# Generated by Django 4.2.5 on 2023-09-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_alter_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-25 21:25:48.553375+00'),
            preserve_default=False,
        ),
    ]
