# Generated by Django 4.2.5 on 2023-09-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_alter_expiringlink_created_at_alter_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiringlink',
            name='created_at',
        ),
    ]
