# Generated by Django 4.2.5 on 2023-09-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_remove_expiringlink_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringLink',
        ),
    ]
