# Generated by Django 4.2.5 on 2023-09-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_delete_expiringlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.image')),
            ],
            options={
                'verbose_name': 'Expiring Link',
                'verbose_name_plural': 'Expiring Links',
            },
        ),
    ]
