version: '3.5'
services:
  db:
    image: postgres:14.3-alpine
    env_file:
      - database.env
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
  web:
    build: ./image_storage
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && ./manage.py shell_plus --print-sql"
    container_name: image_storage
    volumes:
      - ./image_storage:/image_storage_d
    ports:
      - "8000:8000"
    depends_on:
      - db