# Generated by Django 4.2.5 on 2023-09-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_tiers_tier_alter_tier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.tier'),
            preserve_default=False,
        ),
    ]
